services:
  ms-agosto-01-java:
    container_name: ms-agosto-01-java
    image: omarleon/ms-agosto-01:TAG
    ports:
      - "9090:8888"
    environment:
      - MESSAGE=hola microservicio java
      - TZ=Americas/Chicago
    restart: unless-stopped
